--- #YAML:1.0
name:               MCE-Shared
version:            1.000
abstract:           MCE extension for sharing data supporting threads and processes
author:
    - Mario E. Roy <marioeroy AT gmail DOT com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0.45
requires:
    bytes:         0
    Carp:          0
    constant:      0
    MCE:           1.702
    overload:      0
    perl:          5.010001
    POSIX:         0
    Scalar::Util:  0
    Socket:        0
    Storable:      2.04
    strict:        0
    Symbol:        0
    Time::HiRes:   0
    warnings:      0
resources:
    homepage:    https://github.com/marioroy/mce-shared
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/marioroy/mce-shared
provides:
    MCE::Hobo:
        file:     lib/MCE/Hobo.pm
        version:  1.000
    MCE::Shared:
        file:     lib/MCE/Shared.pm
        version:  1.000
    MCE::Shared::Array:
        file:     lib/MCE/Shared/Array.pm
        version:  1.000
    MCE::Shared::Base:
        file:     lib/MCE/Shared/Base.pm
        version:  1.000
    MCE::Shared::Condvar:
        file:     lib/MCE/Shared/Condvar.pm
        version:  1.000
    MCE::Shared::Handle:
        file:     lib/MCE/Shared/Handle.pm
        version:  1.000
    MCE::Shared::Hash:
        file:     lib/MCE/Shared/Hash.pm
        version:  1.000
    MCE::Shared::Minidb:
        file:     lib/MCE/Shared/Minidb.pm
        version:  1.000
    MCE::Shared::Ordhash:
        file:     lib/MCE/Shared/Ordhash.pm
        version:  1.000
    MCE::Shared::Queue:
        file:     lib/MCE/Shared/Queue.pm
        version:  1.000
    MCE::Shared::Scalar:
        file:     lib/MCE/Shared/Scalar.pm
        version:  1.000
    MCE::Shared::Sequence:
        file:     lib/MCE/Shared/Sequence.pm
        version:  1.000
    MCE::Shared::Server:
        file:     lib/MCE/Shared/Server.pm
        version:  1.000
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
